// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ChannelType.
const (
	ChannelTypeHttp     ChannelType = "http"
	ChannelTypeTelegram ChannelType = "telegram"
)

// Valid indicates whether the value is a known member of the ChannelType enum.
func (e ChannelType) Valid() bool {
	switch e {
	case ChannelTypeHttp:
		return true
	case ChannelTypeTelegram:
		return true
	default:
		return false
	}
}

// Defines values for ChannelStatusType.
const (
	ChannelStatusTypeHttp     ChannelStatusType = "http"
	ChannelStatusTypeTelegram ChannelStatusType = "telegram"
)

// Valid indicates whether the value is a known member of the ChannelStatusType enum.
func (e ChannelStatusType) Valid() bool {
	switch e {
	case ChannelStatusTypeHttp:
		return true
	case ChannelStatusTypeTelegram:
		return true
	default:
		return false
	}
}

// Defines values for ConfigDefaultVerdict.
const (
	ConfigDefaultVerdictAllow ConfigDefaultVerdict = "allow"
	ConfigDefaultVerdictAsk   ConfigDefaultVerdict = "ask"
	ConfigDefaultVerdictDeny  ConfigDefaultVerdict = "deny"
)

// Valid indicates whether the value is a known member of the ConfigDefaultVerdict enum.
func (e ConfigDefaultVerdict) Valid() bool {
	switch e {
	case ConfigDefaultVerdictAllow:
		return true
	case ConfigDefaultVerdictAsk:
		return true
	case ConfigDefaultVerdictDeny:
		return true
	default:
		return false
	}
}

// Defines values for ConfigUpdateDefaultVerdict.
const (
	ConfigUpdateDefaultVerdictAllow ConfigUpdateDefaultVerdict = "allow"
	ConfigUpdateDefaultVerdictAsk   ConfigUpdateDefaultVerdict = "ask"
	ConfigUpdateDefaultVerdictDeny  ConfigUpdateDefaultVerdict = "deny"
)

// Valid indicates whether the value is a known member of the ConfigUpdateDefaultVerdict enum.
func (e ConfigUpdateDefaultVerdict) Valid() bool {
	switch e {
	case ConfigUpdateDefaultVerdictAllow:
		return true
	case ConfigUpdateDefaultVerdictAsk:
		return true
	case ConfigUpdateDefaultVerdictDeny:
		return true
	default:
		return false
	}
}

// Defines values for CreateCredentialRequestType.
const (
	CreateCredentialRequestTypeOauth  CreateCredentialRequestType = "oauth"
	CreateCredentialRequestTypeStatic CreateCredentialRequestType = "static"
)

// Valid indicates whether the value is a known member of the CreateCredentialRequestType enum.
func (e CreateCredentialRequestType) Valid() bool {
	switch e {
	case CreateCredentialRequestTypeOauth:
		return true
	case CreateCredentialRequestTypeStatic:
		return true
	default:
		return false
	}
}

// Defines values for CreateRuleRequestVerdict.
const (
	CreateRuleRequestVerdictAllow  CreateRuleRequestVerdict = "allow"
	CreateRuleRequestVerdictAsk    CreateRuleRequestVerdict = "ask"
	CreateRuleRequestVerdictDeny   CreateRuleRequestVerdict = "deny"
	CreateRuleRequestVerdictRedact CreateRuleRequestVerdict = "redact"
)

// Valid indicates whether the value is a known member of the CreateRuleRequestVerdict enum.
func (e CreateRuleRequestVerdict) Valid() bool {
	switch e {
	case CreateRuleRequestVerdictAllow:
		return true
	case CreateRuleRequestVerdictAsk:
		return true
	case CreateRuleRequestVerdictDeny:
		return true
	case CreateRuleRequestVerdictRedact:
		return true
	default:
		return false
	}
}

// Defines values for CredentialType.
const (
	CredentialTypeOauth  CredentialType = "oauth"
	CredentialTypeStatic CredentialType = "static"
)

// Valid indicates whether the value is a known member of the CredentialType enum.
func (e CredentialType) Valid() bool {
	switch e {
	case CredentialTypeOauth:
		return true
	case CredentialTypeStatic:
		return true
	default:
		return false
	}
}

// Defines values for ResolveRequestVerdict.
const (
	ResolveRequestVerdictAllowOnce   ResolveRequestVerdict = "allow_once"
	ResolveRequestVerdictAlwaysAllow ResolveRequestVerdict = "always_allow"
	ResolveRequestVerdictDeny        ResolveRequestVerdict = "deny"
)

// Valid indicates whether the value is a known member of the ResolveRequestVerdict enum.
func (e ResolveRequestVerdict) Valid() bool {
	switch e {
	case ResolveRequestVerdictAllowOnce:
		return true
	case ResolveRequestVerdictAlwaysAllow:
		return true
	case ResolveRequestVerdictDeny:
		return true
	default:
		return false
	}
}

// Defines values for RuleVerdict.
const (
	RuleVerdictAllow  RuleVerdict = "allow"
	RuleVerdictAsk    RuleVerdict = "ask"
	RuleVerdictDeny   RuleVerdict = "deny"
	RuleVerdictRedact RuleVerdict = "redact"
)

// Valid indicates whether the value is a known member of the RuleVerdict enum.
func (e RuleVerdict) Valid() bool {
	switch e {
	case RuleVerdictAllow:
		return true
	case RuleVerdictAsk:
		return true
	case RuleVerdictDeny:
		return true
	case RuleVerdictRedact:
		return true
	default:
		return false
	}
}

// Defines values for GetApiRulesParamsVerdict.
const (
	GetApiRulesParamsVerdictAllow  GetApiRulesParamsVerdict = "allow"
	GetApiRulesParamsVerdictAsk    GetApiRulesParamsVerdict = "ask"
	GetApiRulesParamsVerdictDeny   GetApiRulesParamsVerdict = "deny"
	GetApiRulesParamsVerdictRedact GetApiRulesParamsVerdict = "redact"
)

// Valid indicates whether the value is a known member of the GetApiRulesParamsVerdict enum.
func (e GetApiRulesParamsVerdict) Valid() bool {
	switch e {
	case GetApiRulesParamsVerdictAllow:
		return true
	case GetApiRulesParamsVerdictAsk:
		return true
	case GetApiRulesParamsVerdictDeny:
		return true
	case GetApiRulesParamsVerdictRedact:
		return true
	default:
		return false
	}
}

// Defines values for GetApiRulesParamsType.
const (
	Network GetApiRulesParamsType = "network"
	Pattern GetApiRulesParamsType = "pattern"
	Tool    GetApiRulesParamsType = "tool"
)

// Valid indicates whether the value is a known member of the GetApiRulesParamsType enum.
func (e GetApiRulesParamsType) Valid() bool {
	switch e {
	case Network:
		return true
	case Pattern:
		return true
	case Tool:
		return true
	default:
		return false
	}
}

// ApprovalRequest defines model for ApprovalRequest.
type ApprovalRequest struct {
	CreatedAt   time.Time `json:"created_at"`
	Destination string    `json:"destination"`
	Id          string    `json:"id"`
	Port        int       `json:"port"`
}

// AuditEntry defines model for AuditEntry.
type AuditEntry struct {
	Action         *string   `json:"action,omitempty"`
	CredentialUsed *string   `json:"credential_used,omitempty"`
	Destination    *string   `json:"destination,omitempty"`
	Port           *int      `json:"port,omitempty"`
	PrevHash       *string   `json:"prev_hash,omitempty"`
	Reason         *string   `json:"reason,omitempty"`
	Timestamp      time.Time `json:"timestamp"`
	Tool           *string   `json:"tool,omitempty"`
	Verdict        string    `json:"verdict"`
}

// Binding defines model for Binding.
type Binding struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Credential  string     `json:"credential"`
	Destination string     `json:"destination"`
	Header      *string    `json:"header,omitempty"`
	Id          int64      `json:"id"`
	Ports       *[]int     `json:"ports,omitempty"`
	Protocols   *[]string  `json:"protocols,omitempty"`
	Template    *string    `json:"template,omitempty"`
}

// BrokenLink defines model for BrokenLink.
type BrokenLink struct {
	ActualHash   string `json:"actual_hash"`
	ExpectedHash string `json:"expected_hash"`
	LineNumber   int    `json:"line_number"`
}

// Channel defines model for Channel.
type Channel struct {
	CreatedAt *time.Time  `json:"created_at,omitempty"`
	Enabled   bool        `json:"enabled"`
	Id        int64       `json:"id"`
	Type      ChannelType `json:"type"`

	// WebhookSecret HMAC secret for signing webhook payloads
	WebhookSecret *string `json:"webhook_secret,omitempty"`

	// WebhookUrl Webhook URL for HTTP channels
	WebhookUrl *string `json:"webhook_url,omitempty"`
}

// ChannelType defines model for Channel.Type.
type ChannelType string

// ChannelStatus defines model for ChannelStatus.
type ChannelStatus struct {
	Enabled bool              `json:"enabled"`
	Type    ChannelStatusType `json:"type"`
}

// ChannelStatusType defines model for ChannelStatus.Type.
type ChannelStatusType string

// ChannelUpdate defines model for ChannelUpdate.
type ChannelUpdate struct {
	Enabled       *bool   `json:"enabled,omitempty"`
	WebhookSecret *string `json:"webhook_secret,omitempty"`
	WebhookUrl    *string `json:"webhook_url,omitempty"`
}

// Config defines model for Config.
type Config struct {
	DefaultVerdict *ConfigDefaultVerdict `json:"default_verdict,omitempty"`
	TimeoutSec     *int                  `json:"timeout_sec,omitempty"`
	VaultDir       *string               `json:"vault_dir,omitempty"`
	VaultProvider  *string               `json:"vault_provider,omitempty"`
}

// ConfigDefaultVerdict defines model for Config.DefaultVerdict.
type ConfigDefaultVerdict string

// ConfigUpdate defines model for ConfigUpdate.
type ConfigUpdate struct {
	DefaultVerdict *ConfigUpdateDefaultVerdict `json:"default_verdict,omitempty"`
	TimeoutSec     *int                        `json:"timeout_sec,omitempty"`
}

// ConfigUpdateDefaultVerdict defines model for ConfigUpdate.DefaultVerdict.
type ConfigUpdateDefaultVerdict string

// CreateBindingRequest defines model for CreateBindingRequest.
type CreateBindingRequest struct {
	Credential  string    `json:"credential"`
	Destination string    `json:"destination"`
	Header      *string   `json:"header,omitempty"`
	Ports       *[]int    `json:"ports,omitempty"`
	Protocols   *[]string `json:"protocols,omitempty"`
	Template    *string   `json:"template,omitempty"`
}

// CreateCredentialRequest defines model for CreateCredentialRequest.
type CreateCredentialRequest struct {
	// AccessToken OAuth access token (required when type is oauth)
	AccessToken *string `json:"access_token,omitempty"`

	// Destination If set, also creates an allow rule and binding
	Destination *string `json:"destination,omitempty"`
	Header      *string `json:"header,omitempty"`
	Name        string  `json:"name"`
	Ports       *[]int  `json:"ports,omitempty"`

	// RefreshToken OAuth refresh token (optional, for token rotation)
	RefreshToken *string `json:"refresh_token,omitempty"`
	Template     *string `json:"template,omitempty"`

	// TokenUrl Token endpoint URL (required when type is oauth)
	TokenUrl *string `json:"token_url,omitempty"`

	// Type Credential type. Defaults to static.
	Type *CreateCredentialRequestType `json:"type,omitempty"`

	// Value The credential secret value (stored encrypted). Required for static type.
	Value *string `json:"value,omitempty"`
}

// CreateCredentialRequestType Credential type. Defaults to static.
type CreateCredentialRequestType string

// CreateMCPUpstreamRequest defines model for CreateMCPUpstreamRequest.
type CreateMCPUpstreamRequest struct {
	Args       *[]string          `json:"args,omitempty"`
	Command    string             `json:"command"`
	Env        *map[string]string `json:"env,omitempty"`
	Name       string             `json:"name"`
	TimeoutSec *int               `json:"timeout_sec,omitempty"`

	// Transport Transport type: stdio (default), http, or websocket
	Transport *string `json:"transport,omitempty"`
}

// CreateRuleRequest defines model for CreateRuleRequest.
type CreateRuleRequest struct {
	Destination *string                  `json:"destination,omitempty"`
	Name        *string                  `json:"name,omitempty"`
	Pattern     *string                  `json:"pattern,omitempty"`
	Ports       *[]int                   `json:"ports,omitempty"`
	Protocols   *[]string                `json:"protocols,omitempty"`
	Replacement *string                  `json:"replacement,omitempty"`
	Tool        *string                  `json:"tool,omitempty"`
	Verdict     CreateRuleRequestVerdict `json:"verdict"`
}

// CreateRuleRequestVerdict defines model for CreateRuleRequest.Verdict.
type CreateRuleRequestVerdict string

// Credential defines model for Credential.
type Credential struct {
	Name string `json:"name"`

	// TokenUrl Token endpoint URL (only for oauth type)
	TokenUrl *string `json:"token_url,omitempty"`

	// Type Credential type (static or oauth)
	Type *CredentialType `json:"type,omitempty"`
}

// CredentialType Credential type (static or oauth)
type CredentialType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code  *string `json:"code,omitempty"`
	Error string  `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// ImportResult defines model for ImportResult.
type ImportResult struct {
	BindingsInserted  int `json:"bindings_inserted"`
	BindingsSkipped   int `json:"bindings_skipped"`
	ConfigSet         int `json:"config_set"`
	RulesInserted     int `json:"rules_inserted"`
	RulesSkipped      int `json:"rules_skipped"`
	UpstreamsInserted int `json:"upstreams_inserted"`
	UpstreamsSkipped  int `json:"upstreams_skipped"`
}

// MCPUpstream defines model for MCPUpstream.
type MCPUpstream struct {
	Args       *[]string          `json:"args,omitempty"`
	Command    string             `json:"command"`
	CreatedAt  *time.Time         `json:"created_at,omitempty"`
	Env        *map[string]string `json:"env,omitempty"`
	Id         int64              `json:"id"`
	Name       string             `json:"name"`
	TimeoutSec *int               `json:"timeout_sec,omitempty"`

	// Transport Transport type: stdio, http, or websocket
	Transport *string `json:"transport,omitempty"`
}

// ResolveRequest defines model for ResolveRequest.
type ResolveRequest struct {
	Verdict ResolveRequestVerdict `json:"verdict"`
}

// ResolveRequestVerdict defines model for ResolveRequest.Verdict.
type ResolveRequestVerdict string

// ResolveResponse defines model for ResolveResponse.
type ResolveResponse struct {
	Id      string `json:"id"`
	Verdict string `json:"verdict"`
}

// Rule defines model for Rule.
type Rule struct {
	CreatedAt   *time.Time  `json:"created_at,omitempty"`
	Destination *string     `json:"destination,omitempty"`
	Id          int64       `json:"id"`
	Name        *string     `json:"name,omitempty"`
	Pattern     *string     `json:"pattern,omitempty"`
	Ports       *[]int      `json:"ports,omitempty"`
	Protocols   *[]string   `json:"protocols,omitempty"`
	Replacement *string     `json:"replacement,omitempty"`
	Source      *string     `json:"source,omitempty"`
	Tool        *string     `json:"tool,omitempty"`
	Verdict     RuleVerdict `json:"verdict"`
}

// RuleVerdict defines model for Rule.Verdict.
type RuleVerdict string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Channels         []ChannelStatus `json:"channels"`
	PendingApprovals int             `json:"pending_approvals"`
	ProxyListening   bool            `json:"proxy_listening"`
}

// VerifyResult defines model for VerifyResult.
type VerifyResult struct {
	BrokenLinks []BrokenLink `json:"broken_links"`
	LegacyLines int          `json:"legacy_lines"`
	TotalLines  int          `json:"total_lines"`
	ValidLinks  int          `json:"valid_links"`
}

// GetApiAuditRecentParams defines parameters for GetApiAuditRecent.
type GetApiAuditRecentParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetApiRulesParams defines parameters for GetApiRules.
type GetApiRulesParams struct {
	Verdict *GetApiRulesParamsVerdict `form:"verdict,omitempty" json:"verdict,omitempty"`
	Type    *GetApiRulesParamsType    `form:"type,omitempty" json:"type,omitempty"`
}

// GetApiRulesParamsVerdict defines parameters for GetApiRules.
type GetApiRulesParamsVerdict string

// GetApiRulesParamsType defines parameters for GetApiRules.
type GetApiRulesParamsType string

// PostApiRulesImportMultipartBody defines parameters for PostApiRulesImport.
type PostApiRulesImportMultipartBody struct {
	// File TOML config file
	File openapi_types.File `json:"file"`
}

// PostApiApprovalsIdResolveJSONRequestBody defines body for PostApiApprovalsIdResolve for application/json ContentType.
type PostApiApprovalsIdResolveJSONRequestBody = ResolveRequest

// PostApiBindingsJSONRequestBody defines body for PostApiBindings for application/json ContentType.
type PostApiBindingsJSONRequestBody = CreateBindingRequest

// PatchApiChannelsIdJSONRequestBody defines body for PatchApiChannelsId for application/json ContentType.
type PatchApiChannelsIdJSONRequestBody = ChannelUpdate

// PatchApiConfigJSONRequestBody defines body for PatchApiConfig for application/json ContentType.
type PatchApiConfigJSONRequestBody = ConfigUpdate

// PostApiCredentialsJSONRequestBody defines body for PostApiCredentials for application/json ContentType.
type PostApiCredentialsJSONRequestBody = CreateCredentialRequest

// PostApiMcpUpstreamsJSONRequestBody defines body for PostApiMcpUpstreams for application/json ContentType.
type PostApiMcpUpstreamsJSONRequestBody = CreateMCPUpstreamRequest

// PostApiRulesJSONRequestBody defines body for PostApiRules for application/json ContentType.
type PostApiRulesJSONRequestBody = CreateRuleRequest

// PostApiRulesImportMultipartRequestBody defines body for PostApiRulesImport for multipart/form-data ContentType.
type PostApiRulesImportMultipartRequestBody PostApiRulesImportMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List pending approval requests
	// (GET /api/approvals)
	GetApiApprovals(w http.ResponseWriter, r *http.Request)
	// Resolve a pending approval request
	// (POST /api/approvals/{id}/resolve)
	PostApiApprovalsIdResolve(w http.ResponseWriter, r *http.Request, id string)
	// Recent audit log entries
	// (GET /api/audit/recent)
	GetApiAuditRecent(w http.ResponseWriter, r *http.Request, params GetApiAuditRecentParams)
	// Verify audit log hash chain
	// (GET /api/audit/verify)
	GetApiAuditVerify(w http.ResponseWriter, r *http.Request)
	// List credential bindings
	// (GET /api/bindings)
	GetApiBindings(w http.ResponseWriter, r *http.Request)
	// Add a credential binding
	// (POST /api/bindings)
	PostApiBindings(w http.ResponseWriter, r *http.Request)
	// Remove a credential binding
	// (DELETE /api/bindings/{id})
	DeleteApiBindingsId(w http.ResponseWriter, r *http.Request, id int64)
	// List notification channels
	// (GET /api/channels)
	GetApiChannels(w http.ResponseWriter, r *http.Request)
	// Update a notification channel
	// (PATCH /api/channels/{id})
	PatchApiChannelsId(w http.ResponseWriter, r *http.Request, id int64)
	// Get current configuration
	// (GET /api/config)
	GetApiConfig(w http.ResponseWriter, r *http.Request)
	// Update configuration
	// (PATCH /api/config)
	PatchApiConfig(w http.ResponseWriter, r *http.Request)
	// List credential names
	// (GET /api/credentials)
	GetApiCredentials(w http.ResponseWriter, r *http.Request)
	// Add a credential
	// (POST /api/credentials)
	PostApiCredentials(w http.ResponseWriter, r *http.Request)
	// Remove a credential
	// (DELETE /api/credentials/{name})
	DeleteApiCredentialsName(w http.ResponseWriter, r *http.Request, name string)
	// List MCP upstreams
	// (GET /api/mcp/upstreams)
	GetApiMcpUpstreams(w http.ResponseWriter, r *http.Request)
	// Add an MCP upstream
	// (POST /api/mcp/upstreams)
	PostApiMcpUpstreams(w http.ResponseWriter, r *http.Request)
	// Remove an MCP upstream
	// (DELETE /api/mcp/upstreams/{name})
	DeleteApiMcpUpstreamsName(w http.ResponseWriter, r *http.Request, name string)
	// List policy rules
	// (GET /api/rules)
	GetApiRules(w http.ResponseWriter, r *http.Request, params GetApiRulesParams)
	// Add a policy rule
	// (POST /api/rules)
	PostApiRules(w http.ResponseWriter, r *http.Request)
	// Export rules as TOML
	// (GET /api/rules/export)
	GetApiRulesExport(w http.ResponseWriter, r *http.Request)
	// Import rules from TOML
	// (POST /api/rules/import)
	PostApiRulesImport(w http.ResponseWriter, r *http.Request)
	// Remove a policy rule
	// (DELETE /api/rules/{id})
	DeleteApiRulesId(w http.ResponseWriter, r *http.Request, id int64)
	// Proxy status and stats
	// (GET /api/status)
	GetApiStatus(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List pending approval requests
// (GET /api/approvals)
func (_ Unimplemented) GetApiApprovals(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resolve a pending approval request
// (POST /api/approvals/{id}/resolve)
func (_ Unimplemented) PostApiApprovalsIdResolve(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Recent audit log entries
// (GET /api/audit/recent)
func (_ Unimplemented) GetApiAuditRecent(w http.ResponseWriter, r *http.Request, params GetApiAuditRecentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify audit log hash chain
// (GET /api/audit/verify)
func (_ Unimplemented) GetApiAuditVerify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List credential bindings
// (GET /api/bindings)
func (_ Unimplemented) GetApiBindings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a credential binding
// (POST /api/bindings)
func (_ Unimplemented) PostApiBindings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a credential binding
// (DELETE /api/bindings/{id})
func (_ Unimplemented) DeleteApiBindingsId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List notification channels
// (GET /api/channels)
func (_ Unimplemented) GetApiChannels(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a notification channel
// (PATCH /api/channels/{id})
func (_ Unimplemented) PatchApiChannelsId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current configuration
// (GET /api/config)
func (_ Unimplemented) GetApiConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update configuration
// (PATCH /api/config)
func (_ Unimplemented) PatchApiConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List credential names
// (GET /api/credentials)
func (_ Unimplemented) GetApiCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a credential
// (POST /api/credentials)
func (_ Unimplemented) PostApiCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a credential
// (DELETE /api/credentials/{name})
func (_ Unimplemented) DeleteApiCredentialsName(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List MCP upstreams
// (GET /api/mcp/upstreams)
func (_ Unimplemented) GetApiMcpUpstreams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add an MCP upstream
// (POST /api/mcp/upstreams)
func (_ Unimplemented) PostApiMcpUpstreams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove an MCP upstream
// (DELETE /api/mcp/upstreams/{name})
func (_ Unimplemented) DeleteApiMcpUpstreamsName(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List policy rules
// (GET /api/rules)
func (_ Unimplemented) GetApiRules(w http.ResponseWriter, r *http.Request, params GetApiRulesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a policy rule
// (POST /api/rules)
func (_ Unimplemented) PostApiRules(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export rules as TOML
// (GET /api/rules/export)
func (_ Unimplemented) GetApiRulesExport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Import rules from TOML
// (POST /api/rules/import)
func (_ Unimplemented) PostApiRulesImport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a policy rule
// (DELETE /api/rules/{id})
func (_ Unimplemented) DeleteApiRulesId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Proxy status and stats
// (GET /api/status)
func (_ Unimplemented) GetApiStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiApprovals operation middleware
func (siw *ServerInterfaceWrapper) GetApiApprovals(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiApprovals(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiApprovalsIdResolve operation middleware
func (siw *ServerInterfaceWrapper) PostApiApprovalsIdResolve(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiApprovalsIdResolve(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuditRecent operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuditRecent(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiAuditRecentParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuditRecent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuditVerify operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuditVerify(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuditVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiBindings operation middleware
func (siw *ServerInterfaceWrapper) GetApiBindings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiBindings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiBindings operation middleware
func (siw *ServerInterfaceWrapper) PostApiBindings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiBindings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiBindingsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiBindingsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiBindingsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiChannels operation middleware
func (siw *ServerInterfaceWrapper) GetApiChannels(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiChannelsId operation middleware
func (siw *ServerInterfaceWrapper) PatchApiChannelsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiChannelsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiConfig operation middleware
func (siw *ServerInterfaceWrapper) GetApiConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiConfig operation middleware
func (siw *ServerInterfaceWrapper) PatchApiConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetApiCredentials(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiCredentials operation middleware
func (siw *ServerInterfaceWrapper) PostApiCredentials(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiCredentialsName operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiCredentialsName(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiCredentialsName(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiMcpUpstreams operation middleware
func (siw *ServerInterfaceWrapper) GetApiMcpUpstreams(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiMcpUpstreams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiMcpUpstreams operation middleware
func (siw *ServerInterfaceWrapper) PostApiMcpUpstreams(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiMcpUpstreams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiMcpUpstreamsName operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiMcpUpstreamsName(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiMcpUpstreamsName(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiRules operation middleware
func (siw *ServerInterfaceWrapper) GetApiRules(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiRulesParams

	// ------------- Optional query parameter "verdict" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "verdict", r.URL.Query(), &params.Verdict, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "verdict", Err: err})
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiRules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiRules operation middleware
func (siw *ServerInterfaceWrapper) PostApiRules(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiRules(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiRulesExport operation middleware
func (siw *ServerInterfaceWrapper) GetApiRulesExport(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiRulesExport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiRulesImport operation middleware
func (siw *ServerInterfaceWrapper) PostApiRulesImport(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiRulesImport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiRulesId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiRulesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiRulesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiStatus operation middleware
func (siw *ServerInterfaceWrapper) GetApiStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/approvals", wrapper.GetApiApprovals)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/approvals/{id}/resolve", wrapper.PostApiApprovalsIdResolve)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/audit/recent", wrapper.GetApiAuditRecent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/audit/verify", wrapper.GetApiAuditVerify)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/bindings", wrapper.GetApiBindings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/bindings", wrapper.PostApiBindings)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/bindings/{id}", wrapper.DeleteApiBindingsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/channels", wrapper.GetApiChannels)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/channels/{id}", wrapper.PatchApiChannelsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/config", wrapper.GetApiConfig)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/config", wrapper.PatchApiConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/credentials", wrapper.GetApiCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/credentials", wrapper.PostApiCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/credentials/{name}", wrapper.DeleteApiCredentialsName)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/mcp/upstreams", wrapper.GetApiMcpUpstreams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/mcp/upstreams", wrapper.PostApiMcpUpstreams)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/mcp/upstreams/{name}", wrapper.DeleteApiMcpUpstreamsName)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/rules", wrapper.GetApiRules)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/rules", wrapper.PostApiRules)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/rules/export", wrapper.GetApiRulesExport)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/rules/import", wrapper.PostApiRulesImport)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/rules/{id}", wrapper.DeleteApiRulesId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/status", wrapper.GetApiStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RbXW/bOtL+K4Te96IF3Ng97dnF+i7NCU6DTdogTXcvisBgpHHME4pUScqNN/B/X/BD",
	"EiVRH25jJ3uXSENy5pmZZ4YU/RjFPM04A6ZkNH+MZLyCFJs/j7NM8DWmV/A9B6n0o0zwDIQiYARiAVhB",
	"ssDm3ZKLVP8VJVjBG0VSiCaR2mQQzSOpBGF30XYSJSAVYVgRzvSg1nuSBB9nXCjvBWEK7kBE2+0kEvA9",
	"JwKSaP5Nj64v4UZOfF1vSrX47V8QKz3/cZ4QdcqU2LTNxHGntrGABJgimC5yCWHVhyzuMm0SZQLWixWW",
	"q+A4AVh2TKnBlwqn2Xi/KM5pcK41iITEKvCugX21aDUoBPUHwhI9/knCqXLAT2G/ApyA6AnEUgvC1N/e",
	"Vxr4XuLCpg5RkMqwJ90TLATeWM9yxWNOg+M8pzSGKUgzihUMOyOQCB5UQbcIfg/snLD7YAbkmHaHIjxk",
	"EGvXdUpQwmDB8vS2hnZXGvvSzdknNW1ClpysMGNAnybAgOFbWsvsW84pYLZTjNgnjxGwPDW5AhTuBE6j",
	"SbRSKvPMqFb+Abcrzu8XEmIBRuMEZCxIZqM5+nhxfILsS7TkAklyxwi7Q24cyvCGcpzIqGfuXND2xP92",
	"E3y9OjcTf7y+vkSxBTUwWyjyjEgFXo+Xviisctn2VS/uu8PZ5KrR+n3NEpdwO+jXdt2QB9rqthXibEkC",
	"tJnAEudULTyiLnDBlPIfhgjYRieOvA9Gmo59niutbpi+1maBhISZ0r7VvQIJk2m3NV3o7t2moEqGHlx5",
	"6mt69lRxXmQh2amGWARPSqFOEHEcg5QLpUtOm4A+H+dqhawMMjLoVaET+rEChvTKiEjEca5Wr0f0mfUF",
	"zpZIgpogTCVHtipIhBkysYVETgFhlqBb16lMdnIjwyk8mX8FLAXIVT9STqiAipu3mE4Me9uHgiuDRRCr",
	"nmjQjeE9sHChuDZTA0syTpgy9WJnPxVU7jLevMOKxLZ98RarosrMeoT+sCN0hCA75shQuqWJchazdJAi",
	"1pjmELBqBaiK86LCGmH0SiqujQMWi02mIHl9hK4Ki00RNstaDQdLpYmU7jy6OLn8mkklAKfdiSTudkz9",
	"mKcpZuGtCrC1mTRJiA2hy9piXXNXinfG/mCJUQIzWWyFGg4pXhlY50iqhHD0ykXM6wnSNX+CuNCtj+Tx",
	"Pahx0FdgdDvhKqfQif4Q2XdTAVYKBHvuMiAgoziGFJjqyP3hTWFPXdYLJLi2DexwR99+8aRWcOsO6I63",
	"3ViLM7ox+WvYwsTZAFv1UJNmCcMCxXyvd+GlsRxxKgQXVyAzzmSgg4p5EkYG9Ljhum/FQgt/BEzVqntl",
	"WXb08IDTjJrR94MZ6YaFVjxLdU5cgTQFormeq9JyQZgEoWo9uZcypZi8J1nWJRWbtnQhoeNIRvcGQytZ",
	"md5lcsfrQ1NVcj3TNYBsqNjUZxIALIBOUMeQQjXMQt7zyti+69fPbfB/seaNPgQ4XHH8qZJoNu4j6uIV",
	"SE7X3UWxqzYsOIv13Jj+wBu5qNWLXyoQpUJdjNRxpjz6ZNMg06tBTuGQx+O/Emz/I62H5LmI4Xm7kkG/",
	"28OrniJcHJr50Py/gGU0j/5vWn14mbqvLtP6oVgIbTA8vcDu24zs+nLAHzYLSqQC5s7am6dUDVubI0JL",
	"TSqDQmj8CwRZbjrLtDlfXlDC7sfj4R1KB8CgcIdjrTSDrmDlCtM+gTWmJKmUGiit/nT1sZO6fQ3d2mjp",
	"CIc4F0RtvmhbHUaABQi9p28T/fHlmdvLS70dJRh9Of96dnK6OL48W1x//ufpJwRsjdZYRBP7Fc+428xY",
	"MYQ5Ht3q5Qlb8vYqV6dfrpFeSjfDKWb4jrA7pFaAvtCcxP7O+A1h2hb9vggRZKJIb3wpicGlhGWi6OLs",
	"2tY6ZTpCN90JZ0pwii4pZqAXthknrTZvj2ZHMz2KZ8BwRqJ59O5odvQuMjS2MphNcUamtXS4s82bDj5D",
	"pGdJNI/+BHWckWMvloVLWzPmt9nMds1MOUbCWUZJbCaY/uU+tNmwHB29zQ+orRDebpunHJc26SpEhR0r",
	"bcjkaYrFJppH50QqlHUKTyKFdWP1LaqQudEz1NGaPpJkOxW2fpqU5TKA3SWXNfDOEldyjR8ETkGB0Ks9",
	"RkQboX1T9BJzy6JVFimRw8RDsknBN1YYpPrAk81OTunzRaNr2dZTWyu1/cWQGLW6qxQBzx9XTjSyiQ6X",
	"97P3T6ZDfcPYpwHjCi15zpwK/3gGFTAVgJNNCYZuZXXPlCCeq0YuOHAR7kyIoXzIE6KmAmJnYB+BaNEr",
	"KxkO/u85iE0V/ZSkREV+wJcnnb/PJlGKH0iqW5W3s5n+lzD3b7uns5mxd86qLkKMoCuLBDIAImBK6GLf",
	"9I4nQvldKeb5RL9r+WNt2okx/rCNR7TH/K21NgEczHs3tY5ZK+bDYGfwYFhhuULxChPWg0SxLR9A4UMh",
	"dogIKe5vjAgP72CstCRQx+KAWIVJ+ejG7FB6ClQNhqcvIcHvg6MKydsn06EEvw22e+W+Zznunh2Ou8+Y",
	"aYhLzq07+jhJEA54OuzoZvybRsWSJwX7oaoeAX+Y514MnCVP0ZwMbrQDpPy+3VUXrhGQ8ueo7MX6XmFv",
	"cLTW6yf8429we/jppLo8sn9+Kq7/jOCnT1xVtF3aEmAoFhSsoKn2xS1oytDNsIpXAe7Sjz2MDhq4eyDJ",
	"2rWZA7fZpesDpci+QrlR7PApWKzflYIWMISDoTYQaeXFoL4UtEL7BN+uELI9F0L3gHEh4Rv+JygU1wRy",
	"UVw3KY22A2/s8WVvFlVm7iG2/TtLhw7tbnTNm3pgv5iy78J60LFlLJcFaLCmeJIHKSvVZ+jdOl9N2BK9",
	"MhdIJMICEIM1CAQPGZeQvB7oiM1wHzLP7sGOuAnSvpri9pWvA/fFvnd6vYGT5CUkyYHPVXwA3MkKPJD2",
	"sWKzS++Mu0C+Th91qI7r0r24/GS/OA53PO7T5I4niUOtuYfMc3XnPleMb9AHXZPG2bT8XD9Aphdx9rUU",
	"PQSb+pcCRtDpxcklqmwJEGZdoIImjbNhlmxZvy+aDNzoOzBP1nBv41y8ezmHCAcmyhKAYZpktaBrxVww",
	"DXfhSD8qn5kkS1SeiyJLBYYIcqRTzJWoAU68MjKjDvmLOwI+0D97AyG8gvvBSnt6BuoHF+Z6Hec0qu53",
	"BOY+yAcEcxdmzJdOTkm8QdYToY+b/vvKj/b/QUovnLc/LvcvBh+YxC3Ega8xOYUXffzr+TTg0lpyTvX2",
	"SKgxOXr64H7ju0NwK57SuvHNZGkZeP354hw5rerGWQVsqCIskZYctI+khX3DgWwvwPaGc5pTRTIs1HTJ",
	"RfomwQrX7avfxlkSGvrpgzbR7smRkZhUB4m3hGHDSP13psywwH2Xgx6W1C4Mh2I1tQ5zAs+UKSZM6pFU",
	"KGYiaSl4Oi6WRn8dsdH0kj6NGM56rrbCLD645xrHWtW19x6+chf79hj6jSuJPaex5q4WcmrXTb/0Xplf",
	"wuk//SpcXNY31q/MDwL+02f6RyeyR8MbP0sIdRzGKiKRVdhccPh99u5w4VYqoEPObC9qFwGj+bcb3wvW",
	"IhSvIL73sLfaa+zrY+vXB7/d6PyTINZFitd1Oecxpg6J6fHlGbKi0SQyP5oxFwXn0+nb3/5+NDuaHb2d",
	"v5vNZtH2ZvvfAAAA//+J5Z7DMUQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
