// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ChannelType.
const (
	ChannelTypeHttp     ChannelType = "http"
	ChannelTypeTelegram ChannelType = "telegram"
)

// Valid indicates whether the value is a known member of the ChannelType enum.
func (e ChannelType) Valid() bool {
	switch e {
	case ChannelTypeHttp:
		return true
	case ChannelTypeTelegram:
		return true
	default:
		return false
	}
}

// Defines values for ChannelStatusType.
const (
	ChannelStatusTypeHttp     ChannelStatusType = "http"
	ChannelStatusTypeTelegram ChannelStatusType = "telegram"
)

// Valid indicates whether the value is a known member of the ChannelStatusType enum.
func (e ChannelStatusType) Valid() bool {
	switch e {
	case ChannelStatusTypeHttp:
		return true
	case ChannelStatusTypeTelegram:
		return true
	default:
		return false
	}
}

// Defines values for ConfigDefaultVerdict.
const (
	ConfigDefaultVerdictAllow ConfigDefaultVerdict = "allow"
	ConfigDefaultVerdictAsk   ConfigDefaultVerdict = "ask"
	ConfigDefaultVerdictDeny  ConfigDefaultVerdict = "deny"
)

// Valid indicates whether the value is a known member of the ConfigDefaultVerdict enum.
func (e ConfigDefaultVerdict) Valid() bool {
	switch e {
	case ConfigDefaultVerdictAllow:
		return true
	case ConfigDefaultVerdictAsk:
		return true
	case ConfigDefaultVerdictDeny:
		return true
	default:
		return false
	}
}

// Defines values for ConfigUpdateDefaultVerdict.
const (
	ConfigUpdateDefaultVerdictAllow ConfigUpdateDefaultVerdict = "allow"
	ConfigUpdateDefaultVerdictAsk   ConfigUpdateDefaultVerdict = "ask"
	ConfigUpdateDefaultVerdictDeny  ConfigUpdateDefaultVerdict = "deny"
)

// Valid indicates whether the value is a known member of the ConfigUpdateDefaultVerdict enum.
func (e ConfigUpdateDefaultVerdict) Valid() bool {
	switch e {
	case ConfigUpdateDefaultVerdictAllow:
		return true
	case ConfigUpdateDefaultVerdictAsk:
		return true
	case ConfigUpdateDefaultVerdictDeny:
		return true
	default:
		return false
	}
}

// Defines values for CreateCredentialRequestType.
const (
	CreateCredentialRequestTypeOauth  CreateCredentialRequestType = "oauth"
	CreateCredentialRequestTypeStatic CreateCredentialRequestType = "static"
)

// Valid indicates whether the value is a known member of the CreateCredentialRequestType enum.
func (e CreateCredentialRequestType) Valid() bool {
	switch e {
	case CreateCredentialRequestTypeOauth:
		return true
	case CreateCredentialRequestTypeStatic:
		return true
	default:
		return false
	}
}

// Defines values for CreateRuleRequestVerdict.
const (
	CreateRuleRequestVerdictAllow  CreateRuleRequestVerdict = "allow"
	CreateRuleRequestVerdictAsk    CreateRuleRequestVerdict = "ask"
	CreateRuleRequestVerdictDeny   CreateRuleRequestVerdict = "deny"
	CreateRuleRequestVerdictRedact CreateRuleRequestVerdict = "redact"
)

// Valid indicates whether the value is a known member of the CreateRuleRequestVerdict enum.
func (e CreateRuleRequestVerdict) Valid() bool {
	switch e {
	case CreateRuleRequestVerdictAllow:
		return true
	case CreateRuleRequestVerdictAsk:
		return true
	case CreateRuleRequestVerdictDeny:
		return true
	case CreateRuleRequestVerdictRedact:
		return true
	default:
		return false
	}
}

// Defines values for CredentialType.
const (
	CredentialTypeOauth  CredentialType = "oauth"
	CredentialTypeStatic CredentialType = "static"
)

// Valid indicates whether the value is a known member of the CredentialType enum.
func (e CredentialType) Valid() bool {
	switch e {
	case CredentialTypeOauth:
		return true
	case CredentialTypeStatic:
		return true
	default:
		return false
	}
}

// Defines values for ResolveRequestVerdict.
const (
	ResolveRequestVerdictAllowOnce   ResolveRequestVerdict = "allow_once"
	ResolveRequestVerdictAlwaysAllow ResolveRequestVerdict = "always_allow"
	ResolveRequestVerdictDeny        ResolveRequestVerdict = "deny"
)

// Valid indicates whether the value is a known member of the ResolveRequestVerdict enum.
func (e ResolveRequestVerdict) Valid() bool {
	switch e {
	case ResolveRequestVerdictAllowOnce:
		return true
	case ResolveRequestVerdictAlwaysAllow:
		return true
	case ResolveRequestVerdictDeny:
		return true
	default:
		return false
	}
}

// Defines values for RuleVerdict.
const (
	RuleVerdictAllow  RuleVerdict = "allow"
	RuleVerdictAsk    RuleVerdict = "ask"
	RuleVerdictDeny   RuleVerdict = "deny"
	RuleVerdictRedact RuleVerdict = "redact"
)

// Valid indicates whether the value is a known member of the RuleVerdict enum.
func (e RuleVerdict) Valid() bool {
	switch e {
	case RuleVerdictAllow:
		return true
	case RuleVerdictAsk:
		return true
	case RuleVerdictDeny:
		return true
	case RuleVerdictRedact:
		return true
	default:
		return false
	}
}

// Defines values for GetApiRulesParamsVerdict.
const (
	GetApiRulesParamsVerdictAllow  GetApiRulesParamsVerdict = "allow"
	GetApiRulesParamsVerdictAsk    GetApiRulesParamsVerdict = "ask"
	GetApiRulesParamsVerdictDeny   GetApiRulesParamsVerdict = "deny"
	GetApiRulesParamsVerdictRedact GetApiRulesParamsVerdict = "redact"
)

// Valid indicates whether the value is a known member of the GetApiRulesParamsVerdict enum.
func (e GetApiRulesParamsVerdict) Valid() bool {
	switch e {
	case GetApiRulesParamsVerdictAllow:
		return true
	case GetApiRulesParamsVerdictAsk:
		return true
	case GetApiRulesParamsVerdictDeny:
		return true
	case GetApiRulesParamsVerdictRedact:
		return true
	default:
		return false
	}
}

// Defines values for GetApiRulesParamsType.
const (
	Network GetApiRulesParamsType = "network"
	Pattern GetApiRulesParamsType = "pattern"
	Tool    GetApiRulesParamsType = "tool"
)

// Valid indicates whether the value is a known member of the GetApiRulesParamsType enum.
func (e GetApiRulesParamsType) Valid() bool {
	switch e {
	case Network:
		return true
	case Pattern:
		return true
	case Tool:
		return true
	default:
		return false
	}
}

// ApprovalRequest defines model for ApprovalRequest.
type ApprovalRequest struct {
	CreatedAt   time.Time `json:"created_at"`
	Destination string    `json:"destination"`
	Id          string    `json:"id"`
	Port        int       `json:"port"`
}

// AuditEntry defines model for AuditEntry.
type AuditEntry struct {
	Action         *string   `json:"action,omitempty"`
	CredentialUsed *string   `json:"credential_used,omitempty"`
	Destination    *string   `json:"destination,omitempty"`
	Port           *int      `json:"port,omitempty"`
	PrevHash       *string   `json:"prev_hash,omitempty"`
	Reason         *string   `json:"reason,omitempty"`
	Timestamp      time.Time `json:"timestamp"`
	Tool           *string   `json:"tool,omitempty"`
	Verdict        string    `json:"verdict"`
}

// Binding defines model for Binding.
type Binding struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Credential  string     `json:"credential"`
	Destination string     `json:"destination"`

	// EnvVar Environment variable name for phantom token injection
	EnvVar    *string   `json:"env_var,omitempty"`
	Header    *string   `json:"header,omitempty"`
	Id        int64     `json:"id"`
	Ports     *[]int    `json:"ports,omitempty"`
	Protocols *[]string `json:"protocols,omitempty"`
	Template  *string   `json:"template,omitempty"`
}

// BindingUpdate Partial update for a binding. At least one field must be set in the
// request body, otherwise the server returns 400 Bad Request (matching
// the CLI). Only fields that are present are modified. Setting
// `destination` to a non-empty value also updates the paired
// auto-created allow rule (tagged with `binding-add:<credential>` or
// `cred-add:<credential>`) so the new destination is not orphaned. If
// the paired rule has been removed manually, the binding destination
// is still updated and a warning is logged (no fallback rule is
// created). Passing an empty array for `ports` or `protocols` clears
// them. Passing an empty string for `header`, `template`, or `env_var`
// clears the field. Updating `destination` to a value that collides
// with another binding on the same credential returns 409 Conflict.
type BindingUpdate struct {
	Destination *string `json:"destination,omitempty"`

	// EnvVar Environment variable name for phantom token injection
	EnvVar    *string   `json:"env_var,omitempty"`
	Header    *string   `json:"header,omitempty"`
	Ports     *[]int    `json:"ports,omitempty"`
	Protocols *[]string `json:"protocols,omitempty"`
	Template  *string   `json:"template,omitempty"`
}

// BrokenLink defines model for BrokenLink.
type BrokenLink struct {
	ActualHash   string `json:"actual_hash"`
	ExpectedHash string `json:"expected_hash"`
	LineNumber   int    `json:"line_number"`
}

// Channel defines model for Channel.
type Channel struct {
	CreatedAt *time.Time  `json:"created_at,omitempty"`
	Enabled   bool        `json:"enabled"`
	Id        int64       `json:"id"`
	Type      ChannelType `json:"type"`

	// WebhookSecret HMAC secret for signing webhook payloads
	WebhookSecret *string `json:"webhook_secret,omitempty"`

	// WebhookUrl Webhook URL for HTTP channels
	WebhookUrl *string `json:"webhook_url,omitempty"`
}

// ChannelType defines model for Channel.Type.
type ChannelType string

// ChannelStatus defines model for ChannelStatus.
type ChannelStatus struct {
	Enabled bool              `json:"enabled"`
	Type    ChannelStatusType `json:"type"`
}

// ChannelStatusType defines model for ChannelStatus.Type.
type ChannelStatusType string

// ChannelUpdate defines model for ChannelUpdate.
type ChannelUpdate struct {
	Enabled       *bool   `json:"enabled,omitempty"`
	WebhookSecret *string `json:"webhook_secret,omitempty"`
	WebhookUrl    *string `json:"webhook_url,omitempty"`
}

// Config defines model for Config.
type Config struct {
	DefaultVerdict *ConfigDefaultVerdict `json:"default_verdict,omitempty"`
	TimeoutSec     *int                  `json:"timeout_sec,omitempty"`
	VaultDir       *string               `json:"vault_dir,omitempty"`
	VaultProvider  *string               `json:"vault_provider,omitempty"`
}

// ConfigDefaultVerdict defines model for Config.DefaultVerdict.
type ConfigDefaultVerdict string

// ConfigUpdate defines model for ConfigUpdate.
type ConfigUpdate struct {
	DefaultVerdict *ConfigUpdateDefaultVerdict `json:"default_verdict,omitempty"`
	TimeoutSec     *int                        `json:"timeout_sec,omitempty"`
}

// ConfigUpdateDefaultVerdict defines model for ConfigUpdate.DefaultVerdict.
type ConfigUpdateDefaultVerdict string

// CreateBindingRequest Creates a binding between a credential and a destination. The server
// rejects duplicates: a binding on the same (credential, destination)
// pair may only exist once. Repeated POSTs return 409 Conflict.
type CreateBindingRequest struct {
	Credential  string `json:"credential"`
	Destination string `json:"destination"`

	// EnvVar Environment variable name for phantom token injection
	EnvVar    *string   `json:"env_var,omitempty"`
	Header    *string   `json:"header,omitempty"`
	Ports     *[]int    `json:"ports,omitempty"`
	Protocols *[]string `json:"protocols,omitempty"`
	Template  *string   `json:"template,omitempty"`
}

// CreateCredentialRequest defines model for CreateCredentialRequest.
type CreateCredentialRequest struct {
	// AccessToken OAuth access token (required when type is oauth)
	AccessToken *string `json:"access_token,omitempty"`

	// Destination If set, also creates an allow rule and binding
	Destination *string `json:"destination,omitempty"`

	// EnvVar Environment variable name for phantom token injection into the agent container
	EnvVar *string `json:"env_var,omitempty"`
	Header *string `json:"header,omitempty"`
	Name   string  `json:"name"`
	Ports  *[]int  `json:"ports,omitempty"`

	// RefreshToken OAuth refresh token (optional, for token rotation)
	RefreshToken *string `json:"refresh_token,omitempty"`
	Template     *string `json:"template,omitempty"`

	// TokenUrl Token endpoint URL (required when type is oauth)
	TokenUrl *string `json:"token_url,omitempty"`

	// Type Credential type. Defaults to static.
	Type *CreateCredentialRequestType `json:"type,omitempty"`

	// Value The credential secret value (stored encrypted). Required for static type.
	Value *string `json:"value,omitempty"`
}

// CreateCredentialRequestType Credential type. Defaults to static.
type CreateCredentialRequestType string

// CreateMCPUpstreamRequest defines model for CreateMCPUpstreamRequest.
type CreateMCPUpstreamRequest struct {
	Args       *[]string          `json:"args,omitempty"`
	Command    string             `json:"command"`
	Env        *map[string]string `json:"env,omitempty"`
	Name       string             `json:"name"`
	TimeoutSec *int               `json:"timeout_sec,omitempty"`

	// Transport Transport type: stdio (default), http, or websocket
	Transport *string `json:"transport,omitempty"`
}

// CreatePoolRequest defines model for CreatePoolRequest.
type CreatePoolRequest struct {
	// Members Ordered member credential names (failover order)
	Members []string `json:"members"`
	Name    string   `json:"name"`

	// Strategy Pool strategy; defaults to 'failover' when omitted
	Strategy *string `json:"strategy,omitempty"`
}

// CreateRuleRequest defines model for CreateRuleRequest.
type CreateRuleRequest struct {
	Destination *string                  `json:"destination,omitempty"`
	Name        *string                  `json:"name,omitempty"`
	Pattern     *string                  `json:"pattern,omitempty"`
	Ports       *[]int                   `json:"ports,omitempty"`
	Protocols   *[]string                `json:"protocols,omitempty"`
	Replacement *string                  `json:"replacement,omitempty"`
	Tool        *string                  `json:"tool,omitempty"`
	Verdict     CreateRuleRequestVerdict `json:"verdict"`
}

// CreateRuleRequestVerdict defines model for CreateRuleRequest.Verdict.
type CreateRuleRequestVerdict string

// Credential defines model for Credential.
type Credential struct {
	Name string `json:"name"`

	// TokenUrl Token endpoint URL (only for oauth type)
	TokenUrl *string `json:"token_url,omitempty"`

	// Type Credential type (static or oauth)
	Type *CredentialType `json:"type,omitempty"`
}

// CredentialType Credential type (static or oauth)
type CredentialType string

// CredentialUpdate New value for an existing credential. For static credentials, set
// `value`. For OAuth credentials, set `access_token` and optionally
// `refresh_token`. The existing `token_url` is preserved.
//
// PATCH semantics: omitting `refresh_token` for an OAuth credential
// preserves the currently stored refresh token. To explicitly clear
// the refresh token, send an empty string (`"refresh_token": ""`).
// This prevents clients that rotate only the access token from
// silently destroying the stored refresh token.
type CredentialUpdate struct {
	// AccessToken New OAuth access token (for oauth credentials)
	AccessToken *string `json:"access_token,omitempty"`

	// RefreshToken New OAuth refresh token (for oauth credentials). Omit to
	// preserve the existing refresh token. Send an empty string to
	// clear it.
	RefreshToken *string `json:"refresh_token,omitempty"`

	// Value New secret value (for static credentials)
	Value *string `json:"value,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Bindings Bindings that block the operation, populated on the pool-delete 409 (a pool cannot be removed while bindings still reference it). CLI and Telegram render the same list; included here for channel parity.
	Bindings *[]PoolReferencingBinding `json:"bindings,omitempty"`
	Code     *string                   `json:"code,omitempty"`
	Error    string                    `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// ImportResult defines model for ImportResult.
type ImportResult struct {
	BindingsInserted  int `json:"bindings_inserted"`
	BindingsSkipped   int `json:"bindings_skipped"`
	ConfigSet         int `json:"config_set"`
	RulesInserted     int `json:"rules_inserted"`
	RulesSkipped      int `json:"rules_skipped"`
	UpstreamsInserted int `json:"upstreams_inserted"`
	UpstreamsSkipped  int `json:"upstreams_skipped"`
}

// MCPUpstream defines model for MCPUpstream.
type MCPUpstream struct {
	Args       *[]string          `json:"args,omitempty"`
	Command    string             `json:"command"`
	CreatedAt  *time.Time         `json:"created_at,omitempty"`
	Env        *map[string]string `json:"env,omitempty"`
	Id         int64              `json:"id"`
	Name       string             `json:"name"`
	TimeoutSec *int               `json:"timeout_sec,omitempty"`

	// Transport Transport type: stdio, http, or websocket
	Transport *string `json:"transport,omitempty"`
}

// Pool defines model for Pool.
type Pool struct {
	CreatedAt *time.Time   `json:"created_at,omitempty"`
	Members   []PoolMember `json:"members"`
	Name      string       `json:"name"`

	// Strategy Pool strategy (only 'failover' is supported)
	Strategy string `json:"strategy"`
}

// PoolMember defines model for PoolMember.
type PoolMember struct {
	Credential string `json:"credential"`
	Position   int    `json:"position"`
}

// PoolMemberStatus defines model for PoolMemberStatus.
type PoolMemberStatus struct {
	Active            bool       `json:"active"`
	CooldownUntil     *time.Time `json:"cooldown_until,omitempty"`
	Credential        string     `json:"credential"`
	LastFailureReason *string    `json:"last_failure_reason,omitempty"`
	Position          int        `json:"position"`

	// State healthy, cooldown, or healthy (cooldown expired)
	State string `json:"state"`
}

// PoolReferencingBinding defines model for PoolReferencingBinding.
type PoolReferencingBinding struct {
	Destination string `json:"destination"`
	Id          int64  `json:"id"`
}

// PoolRotateResult defines model for PoolRotateResult.
type PoolRotateResult struct {
	// From Member that was active and is now parked
	From        string     `json:"from"`
	ParkedUntil *time.Time `json:"parked_until,omitempty"`
	Pool        string     `json:"pool"`

	// To New active member after the rotation
	To string `json:"to"`
}

// PoolStatus defines model for PoolStatus.
type PoolStatus struct {
	// Active Currently active member credential name
	Active   string             `json:"active"`
	Members  []PoolMemberStatus `json:"members"`
	Name     string             `json:"name"`
	Strategy string             `json:"strategy"`
}

// ResolveRequest defines model for ResolveRequest.
type ResolveRequest struct {
	Verdict ResolveRequestVerdict `json:"verdict"`
}

// ResolveRequestVerdict defines model for ResolveRequest.Verdict.
type ResolveRequestVerdict string

// ResolveResponse defines model for ResolveResponse.
type ResolveResponse struct {
	Id      string `json:"id"`
	Verdict string `json:"verdict"`
}

// Rule defines model for Rule.
type Rule struct {
	CreatedAt   *time.Time  `json:"created_at,omitempty"`
	Destination *string     `json:"destination,omitempty"`
	Id          int64       `json:"id"`
	Name        *string     `json:"name,omitempty"`
	Pattern     *string     `json:"pattern,omitempty"`
	Ports       *[]int      `json:"ports,omitempty"`
	Protocols   *[]string   `json:"protocols,omitempty"`
	Replacement *string     `json:"replacement,omitempty"`
	Source      *string     `json:"source,omitempty"`
	Tool        *string     `json:"tool,omitempty"`
	Verdict     RuleVerdict `json:"verdict"`
}

// RuleVerdict defines model for Rule.Verdict.
type RuleVerdict string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Channels         []ChannelStatus `json:"channels"`
	PendingApprovals int             `json:"pending_approvals"`
	ProxyListening   bool            `json:"proxy_listening"`
}

// VerifyResult defines model for VerifyResult.
type VerifyResult struct {
	BrokenLinks []BrokenLink `json:"broken_links"`
	LegacyLines int          `json:"legacy_lines"`
	TotalLines  int          `json:"total_lines"`
	ValidLinks  int          `json:"valid_links"`
}

// GetApiAuditRecentParams defines parameters for GetApiAuditRecent.
type GetApiAuditRecentParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetApiRulesParams defines parameters for GetApiRules.
type GetApiRulesParams struct {
	Verdict *GetApiRulesParamsVerdict `form:"verdict,omitempty" json:"verdict,omitempty"`
	Type    *GetApiRulesParamsType    `form:"type,omitempty" json:"type,omitempty"`
}

// GetApiRulesParamsVerdict defines parameters for GetApiRules.
type GetApiRulesParamsVerdict string

// GetApiRulesParamsType defines parameters for GetApiRules.
type GetApiRulesParamsType string

// PostApiRulesImportMultipartBody defines parameters for PostApiRulesImport.
type PostApiRulesImportMultipartBody struct {
	// File TOML config file
	File openapi_types.File `json:"file"`
}

// PostApiApprovalsIdResolveJSONRequestBody defines body for PostApiApprovalsIdResolve for application/json ContentType.
type PostApiApprovalsIdResolveJSONRequestBody = ResolveRequest

// PostApiBindingsJSONRequestBody defines body for PostApiBindings for application/json ContentType.
type PostApiBindingsJSONRequestBody = CreateBindingRequest

// PatchApiBindingsIdJSONRequestBody defines body for PatchApiBindingsId for application/json ContentType.
type PatchApiBindingsIdJSONRequestBody = BindingUpdate

// PatchApiChannelsIdJSONRequestBody defines body for PatchApiChannelsId for application/json ContentType.
type PatchApiChannelsIdJSONRequestBody = ChannelUpdate

// PatchApiConfigJSONRequestBody defines body for PatchApiConfig for application/json ContentType.
type PatchApiConfigJSONRequestBody = ConfigUpdate

// PostApiCredentialsJSONRequestBody defines body for PostApiCredentials for application/json ContentType.
type PostApiCredentialsJSONRequestBody = CreateCredentialRequest

// PatchApiCredentialsNameJSONRequestBody defines body for PatchApiCredentialsName for application/json ContentType.
type PatchApiCredentialsNameJSONRequestBody = CredentialUpdate

// PostApiMcpUpstreamsJSONRequestBody defines body for PostApiMcpUpstreams for application/json ContentType.
type PostApiMcpUpstreamsJSONRequestBody = CreateMCPUpstreamRequest

// PostApiPoolsJSONRequestBody defines body for PostApiPools for application/json ContentType.
type PostApiPoolsJSONRequestBody = CreatePoolRequest

// PostApiRulesJSONRequestBody defines body for PostApiRules for application/json ContentType.
type PostApiRulesJSONRequestBody = CreateRuleRequest

// PostApiRulesImportMultipartRequestBody defines body for PostApiRulesImport for multipart/form-data ContentType.
type PostApiRulesImportMultipartRequestBody PostApiRulesImportMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List pending approval requests
	// (GET /api/approvals)
	GetApiApprovals(w http.ResponseWriter, r *http.Request)
	// Resolve a pending approval request
	// (POST /api/approvals/{id}/resolve)
	PostApiApprovalsIdResolve(w http.ResponseWriter, r *http.Request, id string)
	// Recent audit log entries
	// (GET /api/audit/recent)
	GetApiAuditRecent(w http.ResponseWriter, r *http.Request, params GetApiAuditRecentParams)
	// Verify audit log hash chain
	// (GET /api/audit/verify)
	GetApiAuditVerify(w http.ResponseWriter, r *http.Request)
	// List credential bindings
	// (GET /api/bindings)
	GetApiBindings(w http.ResponseWriter, r *http.Request)
	// Add a credential binding
	// (POST /api/bindings)
	PostApiBindings(w http.ResponseWriter, r *http.Request)
	// Remove a credential binding
	// (DELETE /api/bindings/{id})
	DeleteApiBindingsId(w http.ResponseWriter, r *http.Request, id int64)
	// Update a credential binding
	// (PATCH /api/bindings/{id})
	PatchApiBindingsId(w http.ResponseWriter, r *http.Request, id int64)
	// List notification channels
	// (GET /api/channels)
	GetApiChannels(w http.ResponseWriter, r *http.Request)
	// Update a notification channel
	// (PATCH /api/channels/{id})
	PatchApiChannelsId(w http.ResponseWriter, r *http.Request, id int64)
	// Get current configuration
	// (GET /api/config)
	GetApiConfig(w http.ResponseWriter, r *http.Request)
	// Update configuration
	// (PATCH /api/config)
	PatchApiConfig(w http.ResponseWriter, r *http.Request)
	// List credential names
	// (GET /api/credentials)
	GetApiCredentials(w http.ResponseWriter, r *http.Request)
	// Add a credential
	// (POST /api/credentials)
	PostApiCredentials(w http.ResponseWriter, r *http.Request)
	// Remove a credential
	// (DELETE /api/credentials/{name})
	DeleteApiCredentialsName(w http.ResponseWriter, r *http.Request, name string)
	// Replace the value of an existing credential
	// (PATCH /api/credentials/{name})
	PatchApiCredentialsName(w http.ResponseWriter, r *http.Request, name string)
	// List MCP upstreams
	// (GET /api/mcp/upstreams)
	GetApiMcpUpstreams(w http.ResponseWriter, r *http.Request)
	// Add an MCP upstream
	// (POST /api/mcp/upstreams)
	PostApiMcpUpstreams(w http.ResponseWriter, r *http.Request)
	// Remove an MCP upstream
	// (DELETE /api/mcp/upstreams/{name})
	DeleteApiMcpUpstreamsName(w http.ResponseWriter, r *http.Request, name string)
	// List credential pools
	// (GET /api/pools)
	GetApiPools(w http.ResponseWriter, r *http.Request)
	// Create a credential pool
	// (POST /api/pools)
	PostApiPools(w http.ResponseWriter, r *http.Request)
	// Remove a credential pool
	// (DELETE /api/pools/{name})
	DeleteApiPoolsName(w http.ResponseWriter, r *http.Request, name string)
	// Pool status (active member + per-member health)
	// (GET /api/pools/{name})
	GetApiPoolsName(w http.ResponseWriter, r *http.Request, name string)
	// Operator override — advance the active pool member
	// (POST /api/pools/{name}/rotate)
	PostApiPoolsNameRotate(w http.ResponseWriter, r *http.Request, name string)
	// List policy rules
	// (GET /api/rules)
	GetApiRules(w http.ResponseWriter, r *http.Request, params GetApiRulesParams)
	// Add a policy rule
	// (POST /api/rules)
	PostApiRules(w http.ResponseWriter, r *http.Request)
	// Export rules as TOML
	// (GET /api/rules/export)
	GetApiRulesExport(w http.ResponseWriter, r *http.Request)
	// Import rules from TOML
	// (POST /api/rules/import)
	PostApiRulesImport(w http.ResponseWriter, r *http.Request)
	// Remove a policy rule
	// (DELETE /api/rules/{id})
	DeleteApiRulesId(w http.ResponseWriter, r *http.Request, id int64)
	// Proxy status and stats
	// (GET /api/status)
	GetApiStatus(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List pending approval requests
// (GET /api/approvals)
func (_ Unimplemented) GetApiApprovals(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resolve a pending approval request
// (POST /api/approvals/{id}/resolve)
func (_ Unimplemented) PostApiApprovalsIdResolve(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Recent audit log entries
// (GET /api/audit/recent)
func (_ Unimplemented) GetApiAuditRecent(w http.ResponseWriter, r *http.Request, params GetApiAuditRecentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify audit log hash chain
// (GET /api/audit/verify)
func (_ Unimplemented) GetApiAuditVerify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List credential bindings
// (GET /api/bindings)
func (_ Unimplemented) GetApiBindings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a credential binding
// (POST /api/bindings)
func (_ Unimplemented) PostApiBindings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a credential binding
// (DELETE /api/bindings/{id})
func (_ Unimplemented) DeleteApiBindingsId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a credential binding
// (PATCH /api/bindings/{id})
func (_ Unimplemented) PatchApiBindingsId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List notification channels
// (GET /api/channels)
func (_ Unimplemented) GetApiChannels(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a notification channel
// (PATCH /api/channels/{id})
func (_ Unimplemented) PatchApiChannelsId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current configuration
// (GET /api/config)
func (_ Unimplemented) GetApiConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update configuration
// (PATCH /api/config)
func (_ Unimplemented) PatchApiConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List credential names
// (GET /api/credentials)
func (_ Unimplemented) GetApiCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a credential
// (POST /api/credentials)
func (_ Unimplemented) PostApiCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a credential
// (DELETE /api/credentials/{name})
func (_ Unimplemented) DeleteApiCredentialsName(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Replace the value of an existing credential
// (PATCH /api/credentials/{name})
func (_ Unimplemented) PatchApiCredentialsName(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List MCP upstreams
// (GET /api/mcp/upstreams)
func (_ Unimplemented) GetApiMcpUpstreams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add an MCP upstream
// (POST /api/mcp/upstreams)
func (_ Unimplemented) PostApiMcpUpstreams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove an MCP upstream
// (DELETE /api/mcp/upstreams/{name})
func (_ Unimplemented) DeleteApiMcpUpstreamsName(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List credential pools
// (GET /api/pools)
func (_ Unimplemented) GetApiPools(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a credential pool
// (POST /api/pools)
func (_ Unimplemented) PostApiPools(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a credential pool
// (DELETE /api/pools/{name})
func (_ Unimplemented) DeleteApiPoolsName(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Pool status (active member + per-member health)
// (GET /api/pools/{name})
func (_ Unimplemented) GetApiPoolsName(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Operator override — advance the active pool member
// (POST /api/pools/{name}/rotate)
func (_ Unimplemented) PostApiPoolsNameRotate(w http.ResponseWriter, r *http.Request, name string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List policy rules
// (GET /api/rules)
func (_ Unimplemented) GetApiRules(w http.ResponseWriter, r *http.Request, params GetApiRulesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a policy rule
// (POST /api/rules)
func (_ Unimplemented) PostApiRules(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export rules as TOML
// (GET /api/rules/export)
func (_ Unimplemented) GetApiRulesExport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Import rules from TOML
// (POST /api/rules/import)
func (_ Unimplemented) PostApiRulesImport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a policy rule
// (DELETE /api/rules/{id})
func (_ Unimplemented) DeleteApiRulesId(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Proxy status and stats
// (GET /api/status)
func (_ Unimplemented) GetApiStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiApprovals operation middleware
func (siw *ServerInterfaceWrapper) GetApiApprovals(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiApprovals(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiApprovalsIdResolve operation middleware
func (siw *ServerInterfaceWrapper) PostApiApprovalsIdResolve(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiApprovalsIdResolve(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuditRecent operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuditRecent(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiAuditRecentParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuditRecent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiAuditVerify operation middleware
func (siw *ServerInterfaceWrapper) GetApiAuditVerify(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiAuditVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiBindings operation middleware
func (siw *ServerInterfaceWrapper) GetApiBindings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiBindings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiBindings operation middleware
func (siw *ServerInterfaceWrapper) PostApiBindings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiBindings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiBindingsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiBindingsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiBindingsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiBindingsId operation middleware
func (siw *ServerInterfaceWrapper) PatchApiBindingsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiBindingsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiChannels operation middleware
func (siw *ServerInterfaceWrapper) GetApiChannels(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiChannelsId operation middleware
func (siw *ServerInterfaceWrapper) PatchApiChannelsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiChannelsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiConfig operation middleware
func (siw *ServerInterfaceWrapper) GetApiConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiConfig operation middleware
func (siw *ServerInterfaceWrapper) PatchApiConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetApiCredentials(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiCredentials operation middleware
func (siw *ServerInterfaceWrapper) PostApiCredentials(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiCredentialsName operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiCredentialsName(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiCredentialsName(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiCredentialsName operation middleware
func (siw *ServerInterfaceWrapper) PatchApiCredentialsName(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiCredentialsName(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiMcpUpstreams operation middleware
func (siw *ServerInterfaceWrapper) GetApiMcpUpstreams(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiMcpUpstreams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiMcpUpstreams operation middleware
func (siw *ServerInterfaceWrapper) PostApiMcpUpstreams(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiMcpUpstreams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiMcpUpstreamsName operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiMcpUpstreamsName(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiMcpUpstreamsName(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiPools operation middleware
func (siw *ServerInterfaceWrapper) GetApiPools(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiPools(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiPools operation middleware
func (siw *ServerInterfaceWrapper) PostApiPools(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiPools(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiPoolsName operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiPoolsName(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiPoolsName(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiPoolsName operation middleware
func (siw *ServerInterfaceWrapper) GetApiPoolsName(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiPoolsName(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiPoolsNameRotate operation middleware
func (siw *ServerInterfaceWrapper) PostApiPoolsNameRotate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiPoolsNameRotate(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiRules operation middleware
func (siw *ServerInterfaceWrapper) GetApiRules(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiRulesParams

	// ------------- Optional query parameter "verdict" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "verdict", r.URL.Query(), &params.Verdict, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "verdict", Err: err})
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiRules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiRules operation middleware
func (siw *ServerInterfaceWrapper) PostApiRules(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiRules(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiRulesExport operation middleware
func (siw *ServerInterfaceWrapper) GetApiRulesExport(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiRulesExport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiRulesImport operation middleware
func (siw *ServerInterfaceWrapper) PostApiRulesImport(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiRulesImport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiRulesId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiRulesId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiRulesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiStatus operation middleware
func (siw *ServerInterfaceWrapper) GetApiStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/approvals", wrapper.GetApiApprovals)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/approvals/{id}/resolve", wrapper.PostApiApprovalsIdResolve)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/audit/recent", wrapper.GetApiAuditRecent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/audit/verify", wrapper.GetApiAuditVerify)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/bindings", wrapper.GetApiBindings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/bindings", wrapper.PostApiBindings)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/bindings/{id}", wrapper.DeleteApiBindingsId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/bindings/{id}", wrapper.PatchApiBindingsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/channels", wrapper.GetApiChannels)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/channels/{id}", wrapper.PatchApiChannelsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/config", wrapper.GetApiConfig)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/config", wrapper.PatchApiConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/credentials", wrapper.GetApiCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/credentials", wrapper.PostApiCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/credentials/{name}", wrapper.DeleteApiCredentialsName)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/credentials/{name}", wrapper.PatchApiCredentialsName)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/mcp/upstreams", wrapper.GetApiMcpUpstreams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/mcp/upstreams", wrapper.PostApiMcpUpstreams)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/mcp/upstreams/{name}", wrapper.DeleteApiMcpUpstreamsName)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/pools", wrapper.GetApiPools)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/pools", wrapper.PostApiPools)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/pools/{name}", wrapper.DeleteApiPoolsName)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/pools/{name}", wrapper.GetApiPoolsName)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/pools/{name}/rotate", wrapper.PostApiPoolsNameRotate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/rules", wrapper.GetApiRules)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/rules", wrapper.PostApiRules)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/rules/export", wrapper.GetApiRulesExport)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/rules/import", wrapper.PostApiRulesImport)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/rules/{id}", wrapper.DeleteApiRulesId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/status", wrapper.GetApiStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Rd63LbOJZ+FRR3q9quUWT1dM9ujeeX252duDbpuBxn90eUkmDyyMIYBNgAKEebctU+",
	"xD7hPskUDkASlEBSSmw5XfkVi8TlXL5zw4X5nKQyL6QAYXRy+jnR6RJyin+eFYWSK8qv4PcStLGPCiUL",
	"UIYBNkgVUAPZjOK7hVS5/SvJqIEXhuWQjBKzLiA5TbRRTNwmD6MkA22YoIZJYTttvWdZ9HEhlQleMGHg",
	"FlTy8DBKFPxeMgVZcvrB9m5P4XuOQlo/1mTJm39Aauz4Z2XGzEth1HqbTZp2UpsqyEAYRvms1BAnfYjj",
	"LtZGSaFgNVtSvYz2U0B1x5BW+NrQvNhdL0ZKHh1rBSpjqYm825B9M2nTKSbqX5jIbP9HgVOjgC+SPYjV",
	"bEWVfZeBThUrXNPkpVgxJUUOwpAVVYzecCCC5kAWUpFiSYWROTHyDgRhwrLm0LY1wxJoBqoH6jWfTJh/",
	"+7kZIsSBVM44mYFcx7Hin1Cl6NphRxqZSh7tF6h9o5uBvODUwLC6I6YWKKNH8e+LzE/QFvklVbYrKfE9",
	"ypmSG9dnTM4M4UC1IVIAWTDgGclLbcgNEA2GMEHMEqZCOV9FbmS2HhFplqDumQb7kmhQK1BEgSmV0OTn",
	"yYT8QjPi3Rs5yqlJl0zcToVtff764nhM3gq+dtNpYpbUEKqAFAq0BYb9O5cZWzDIxuQdGIO954FU5sRI",
	"QomQ4gXkhVmTFeUlEMq19IxqpK2gVq5TQUsjX3hDIJRzeU9UyYEcGXp7Cxm5Z2ZJ5l4qL2iWnU7LyeSn",
	"tBE9/oY5kWoq5vZxX6tjoiXOL+CeBGQTpomQhkhloW65u1g4sThCHVFLqskNgCAKcrmCjORUlJTz9QjH",
	"9FSG404F00Qbxis1Z4SKjFByT5WwbZkmXCKnR0KSBeX8hqZ3bjqmp8KL5nhMLqnWtgcVxEkWMYywmaPB",
	"WBGQeW0Hc5JyoEojG3mkv8O5G8BZ7XxE5pVBzEc4nHcY86lwoyGjiI8xQWDbISIAcGpHBKWSc5aBngpU",
	"JhWI0lpaUjiwWl/T6CtA7V/JuRQLzlIznmKAaznRb9rjfTOObNs3KcvYaybuovG/pLw7EMOnAlIbuDpb",
	"cCZgJsr8piWXriQmbL05+qhFTczLni+pEMAfJ7yCsDAI85obKTlQsVf8ck8+JyDKHDMF4HCraJ6MkqUx",
	"RcBGM/M93CylvJtpSBWYbbi+enN2TtxLBKhmt+hAfD9S0DWXNNNJz9il4tsD/7cf4P3Vaxz41fX1JUmd",
	"UCOjxaIiNmmE16Old4aaUm/rqlfu+4tzM1Pbmb4mVu9B37bqhjSwg4Fan8ciSWMGC1pyMwvS1EouGD4x",
	"SRFrazj6Loo0i31ZGktu3COtcIKMxX2ae2srJRZ3e93cdEn3yXmKkoTuwedoQcnXtg7XSjeZGbkBc29z",
	"ABpGKxfUg1g0Jtd1BmazNDurJllZcJbaAU+DEcMIeNQMOgrHO54Km4mQnK6JtDkafGKYHKYwJldQuATq",
	"8u27a+1D52Dk/COXEt9khbBXceCAdV436lx0oGkKWs9QXtvCfntW2pwK23iZHlU0kfslCGJntmmmpKVZ",
	"Hu+wRNGe4GJh642Ry+DTyhpEmKtb8Hssx2PqYwKFMGFcCk9vbcdUCkOZwNRhHwTZeR4NWgoWCvSyX0m+",
	"UaUliW+tmVtu3UMljbP26IpFNxBHCfaPB/hrHBpEVkgmDMb5vSFShWDvqfEdNSx1JXHbX1Y+0fYZk19d",
	"DwtO4vqMMRQ7916PglNHXTtWEhGulq1ywWdGruw40kZa5kCkal248umq4hiTJ5zWUTiY4iBSuk34zfnl",
	"+0IbBTTvtmF1u6fXSWWeU5F1eV4cNMuYg9Bla7KusRvCO7E/mBoYRYWuFvA2FFK9QrGeEm0yJsmRR8zx",
	"iNhcDYvKe7jRMr0Ds5voG2F0K+FSym4PmoMtLXTELlUGFhKuQQgnO7EmRwvKuFyBItK2tJaxuwY7hayN",
	"ogZu15EVISk5qV7/jWSB6fxQkfKDM1mZM2Mg21WClQi6JXhVcuiU4FAu0O1MqTGgxHPHcAUFpynYSNPh",
	"PYcXg3syUjtBRlvLvx3q6FsnPm/lY20FdFvsfn4fU0frAdHfoqUO+Pse5279LPrRarzjfTz7Hl7WT9q1",
	"kPob3HvHj2uowuXGNrNuLHpM/qPx+81jPbLZzVTMsf/ctXLherMRmYeZ2ByzniqG8/VUzFtJwNwVADUl",
	"81pRcxtpcUVVrSAbT8VUXJ5dn78iGnIqDEv1qbNu7NYetGJwk8KpqAZ0C3RpqRQIw9fER8JW7jEm15LA",
	"J1uKMNsGV/bcamernWXb1jUbC4ZH82k74Zkmp2SaTJP58XgqrpeOvRUIo0nKGf6LC4GY3YArXzCBC7PW",
	"hZL5VGjGHd3W4yi5tvNhbRRjI1LT9CfLFiixhLkxiEDpUbsYSPSaCTaSvfgMY/I2Z4YY2egPua1Rs6G2",
	"dzF12N6oQcJ8mbdrCmWpbedNi6iNHEejzJahvlRKqivQhRQ6UuT7CiEShn0N7lFyw2V6h2KwvTHmjEgh",
	"i5JjieuL5UJK/iIDDgaw0D2i+IikVAiJuyTVGv39kvF6bb5ajFewAAUiBcLM8Zicv75Ae772K0tEgchA",
	"NWU5Z9r8jTCR8jKDjCxBOWfj18lIQRUz63GYIPyrgkVymvzLSbPffOI3m09cuuJIYOK22iGM5oFZ3PGD",
	"lfZwTeqaxfzqK6DcLLv1peulOvhE84Jj77vBhMN3i814kduQfwUaK4gufMyY0KBMa7EtyAjqZvqOFUVX",
	"qxTXm2YaOnaabd06NJNr0ztN6RP/oaGadj3DbQhyg8RNekYRgUWkE6UxRlBLZjHtBXXOUxc4X7Zy/5VF",
	"0c6r+4ernr6oZsIV+R0Kp0uf8379pklQX+3s/d5gn6eom3ySGxRMTBNdFla4kB3vWjHVs/UXTwEvMVn2",
	"LbAWUrONiqrLFwQjBf366enaaqGpYSuI72SkUvJM3otZKQzjj3YqhVNtZlYfpYJZzzGePomMMLJEspgl",
	"xrH1iFTEo734p+SoemoTXivOYQDEhT2qBFcR0iX9SFzfu57e0RcNnVDpJBET8a5AbDPxbTE7ULkU7Z5q",
	"4qSBWROenbi3OdBdbEVilLg3+4Kq6CrKjYznsp4kv5pDF8ZncNWq6qDmccaREwBO0yXAYdvaKJzreqxN",
	"48aK0+M6V0/kl7rYfb1kbR597vIKtOSr7oWmrvWWmRSpHZvye7rWs9YazFctutQEdaXBHeczdz4liEbZ",
	"S0HJ4ZBHTb8mw/mDLOdpWaoUnnelb1Dvzjy7gVcfwdjV8ttHLGLSBgxHM+rPOeuuU7jy03pmK14QPnpt",
	"ZgqbfnOjR2yqUcNQTBr/BYot1p21IZ5WmnEm7naXR3DEKSIMDrc0tUQL6AKrNJT3NVhRzrKGqIHoHA7X",
	"7jtq87dB27a0LMIhLRUz63eWVy8joArUWWmW2/Hn7PLCr0RpMGTFKHn3+v3F+cvZ2eXF7Prtf778jYBY",
	"kRVV1qfjmFbdOGLjIfCwzYOdnolFJAZfvXx3TexUC6lITgW9rZbv3vGSpeF+3Qu/nytuSQURgigaW/ZZ",
	"Ct4knCdK3lxcuwLL4DKEH+5cCqMkJ5ecCrATO4vTjpofx5PxxPaSBQhasOQ0+Wk8Gf+UoBtbosxOaMFO",
	"WuZw61YM6qWniyw5Tf4O5qxgZwGWlTdb7PPnyQQNVgrjPRIt3DkPJsXJP3y262C5M3o3LyNsQfjhYXPv",
	"9dIZXSNRfzhYO8iUeU7VOjlNXjNtSNHZeJQYaqv5D0kjmY92hLa0Tj6z7OFEufiJJit1RHaXUreEd5H5",
	"kIt6UDQHg+nNh88Js0xY3VQF7Knzoo0VGVXCKJDkpgv+6BqDNr/IbL2XUvp0sZG1PLRN2xL18JWQ2Gl2",
	"Hykimj9rlIhtMwuXnyc/PxoN7bXdPgqENGQhS+FJ+OszkEC5Apqta2HYetDmTBmRpdmwBS9cQjsNYsge",
	"yoyZEwWpZ7DPgdimV65lHPy/l6DWDfo5y5lJQsDX5y/+MhklOf3Ecpuq/DiZ2J9M+J+RSvHjQXxWc6lo",
	"B3flJEFQgASEUTbYb2onaMLlbd0s0Il9t6WPFaYTu+jDJR7JE9pvK7WJyAHf+6EtZl2zUAxuhEAMS6qX",
	"JF1SJnokEW649Eih2n05SFTr3OnYFkuw2VxzEoljaaRZI5P60Ue3vNQdoFpiePwQEj1tulMg+fHRaKiF",
	"vy1s/8of8PO+e3I4330hMCGufe6hY0fFfxU6cAdWu5N5S6Y3j/qGlXYbk2dZ1j4ZHByM3MbkpqliTuX8",
	"PAe32NkG66/4PIDrRfYYedTwSuN2/Pi5cyO32no9eBJSzR/kIBvhxNK1h36wVEiXEadhHz+XGh7fO7Vv",
	"Kh44v93BLfm7c9+GW3peQB/YMf4a3JGsLvIRf4+vOadS3WRw/nLrMt+GGTqYfYGbDJfEejKa8+by0tNn",
	"NNX1sx0ymt+kaRK9mpdITiOiDRvRNCtpW6KpI8iA46pk9Ad3XO1rWwd2XLXqI8mrPxfUclwHdBzV/F2R",
	"sDbBGNQGkFZfTOszQdfoKYXvZojx7jbbSFq1CBn/O5jqdKRvUKp6c7Bi2nXcIfwHbD4BtsM7c4eGdrd0",
	"8c23E5FjsB5UbI3l5pDjEKCDlgcJK0Hw3KtW9jcX8ECnxi82CFiBIvCpkBqy44EaGruHIgv4HqyhN4X0",
	"VGX09q25A1fSoXZ6tUGz7DuspkMBtArqgWK5E3cRez35bKG6W7Ec4PI3d25hOOPxBxz23HsYqpDPww9c",
	"PE+RHPqK3evkPpcwECMPJvwncTftuyc7+Zl+vX+vtexOuMNzHVhCuhsJctFxn2fQVeRpcVKfch4I7m/S",
	"4n3d9BDRPTxLvUN4f3N+SRpeIgG83aARTZ4Ww1F7i/unCtuRm7IHjtstuW/LuXr33S6D1wIYDtuiBbot",
	"zEXNcJ+YHaLymYN2LZXnCtk1AUMBe0elFFIOFjyX2OYQzhAvIuxX5DgG+iuZwjNQicD9HvSGDd9P5QbD",
	"u+oH9n9O1JGTQ3h17jt1esg8fnakXuDGTzH6M9pM197QQgg2bc8ptb2a7Q+Sb0KvZX/7OEME5TN7QRTT",
	"c3lAp6Nn2wXxF4xaN0czcrPGj3NKRXKpmium7uZ3JVD8MucPuv6GpZ77r3ly3GHG70Zymd4F2yiaHLGM",
	"/Kn1+afxDluZHagbDbr5QyJr8qjOrDrs3Kmy6iz0s6K1pbmAMHLUvg7yJ1KAeuF/uBtMxzu6kRN3uX7w",
	"HGatb3cH6I+p9db9pdjJMn/hpz5N9X15Kyceoqh1UpSkUlQ7Hv5qzpIVuNdzCxvYfIuQkYrIFSjFMiD/",
	"/7//R2i2osKX5R6weNfejdYDULyxPJBnXmGbnY5DVrcpQuh96V2N+Az+Q5Hbwwsw91Lh7XfnZKubMJGx",
	"D3LUEm8N7XImXHKWronTROwYePi+0aT7PZgsV8p7umQ5/CzRgZNlJ+KIeZUcvp1kObKgHug0otKWcZ7A",
	"p+o++pCNvvzk/2eBPcBtZM7bzG8ayxaD12/fvCaeqjZzjgAHVUI1sS0H+WN5xd8wkN33KXrhnJfcsIIq",
	"c7KQKn+RUUPb/G1cpWU89uk6y6LbiyTYYtQcoLhhgqJH6r9dht0iN4MOuknc+p5HDKu5U1gQhJ/BUhAm",
	"bSRVhCGSFkrmu2Fp58OZDk3f0slM9FnPVbzh5IN7Tbt5rearND3+ylcFTwj9jcubPadQ8FZbXYi0K4Hg",
	"FR4rtn+GUbj6lg5y7+qB/+lj/ZVv8oSMb3w1KJZxIFdMV59gsHD7y+SnA2bfFQEWcrhw07oymZx++Bhq",
	"wXFE0iWkd4HsHfVW9u2+7YuWHz5a+3OfeXYm3qbltUwp95I4Obu88F+ETkYJfrIPr1Senpz8+Od/H0/G",
	"k/GPpz9NJpPk4ePDPwMAAP//63q4OKdoAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
