package proxy

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"fmt"
	"math/big"
	"net"
	"sync"
	"time"

	"github.com/lqqyt2423/go-mitmproxy/cert"
	"golang.org/x/sync/singleflight"
)

// sluiceCA implements the go-mitmproxy cert.CA interface using an existing
// tls.Certificate generated by sluice's own CA infrastructure. This lets
// go-mitmproxy use the same CA cert and key that sluice already manages
// (including hot-rotation and expiry warnings) instead of generating its
// own separate CA.
type sluiceCA struct {
	rootCert *x509.Certificate
	privKey  crypto.Signer

	cacheMu  sync.RWMutex
	cache    map[string]*tls.Certificate
	certOnce singleflight.Group
}

// Verify interface compliance at compile time.
var _ cert.CA = (*sluiceCA)(nil)

// newSluiceCA wraps an existing tls.Certificate (from LoadOrCreateCA or
// GenerateCA) into a cert.CA for go-mitmproxy.
func newSluiceCA(tlsCert tls.Certificate) (*sluiceCA, error) {
	x509Cert, err := x509.ParseCertificate(tlsCert.Certificate[0])
	if err != nil {
		return nil, err
	}

	signer, ok := tlsCert.PrivateKey.(crypto.Signer)
	if !ok {
		return nil, fmt.Errorf("private key does not implement crypto.Signer")
	}

	return &sluiceCA{
		rootCert: x509Cert,
		privKey:  signer,
		cache:    make(map[string]*tls.Certificate),
	}, nil
}

func (ca *sluiceCA) GetRootCA() *x509.Certificate {
	return ca.rootCert
}

func (ca *sluiceCA) GetCert(commonName string) (*tls.Certificate, error) {
	// Fast path: check cache under read lock.
	ca.cacheMu.RLock()
	if cached, ok := ca.cache[commonName]; ok {
		ca.cacheMu.RUnlock()
		return cached, nil
	}
	ca.cacheMu.RUnlock()

	// Slow path: singleflight ensures only one goroutine generates the
	// cert for a given commonName, eliminating the TOCTOU race between
	// the cache check and the cache store.
	v, err, _ := ca.certOnce.Do(commonName, func() (any, error) {
		// Re-check cache in case another goroutine populated it between
		// the fast-path check and entering singleflight.
		ca.cacheMu.RLock()
		if cached, ok := ca.cache[commonName]; ok {
			ca.cacheMu.RUnlock()
			return cached, nil
		}
		ca.cacheMu.RUnlock()

		cert, err := ca.dummyCert(commonName)
		if err != nil {
			return nil, err
		}

		ca.cacheMu.Lock()
		ca.cache[commonName] = cert
		ca.cacheMu.Unlock()

		return cert, nil
	})
	if err != nil {
		return nil, err
	}

	return v.(*tls.Certificate), nil
}

// dummyCert generates a TLS certificate for the given common name, signed
// by the sluice root CA. Supports both ECDSA and RSA private keys.
func (ca *sluiceCA) dummyCert(commonName string) (*tls.Certificate, error) {
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, fmt.Errorf("generate serial number: %w", err)
	}

	template := &x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			CommonName:   commonName,
			Organization: []string{"sluice"},
		},
		NotBefore:   time.Now().Add(-time.Hour * 48),
		NotAfter:    time.Now().Add(time.Hour * 24 * 365),
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
	}

	// Set the signature algorithm based on the private key type.
	switch ca.privKey.(type) {
	case *ecdsa.PrivateKey:
		template.SignatureAlgorithm = x509.ECDSAWithSHA256
	case *rsa.PrivateKey:
		template.SignatureAlgorithm = x509.SHA256WithRSA
	}

	ip := net.ParseIP(commonName)
	if ip != nil {
		template.IPAddresses = []net.IP{ip}
	} else {
		template.DNSNames = []string{commonName}
	}

	// Generate a fresh ECDSA key for each leaf certificate so that
	// compromising one leaf does not compromise the CA or other leaves.
	leafKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("generate leaf key: %w", err)
	}

	certBytes, err := x509.CreateCertificate(rand.Reader, template, ca.rootCert, &leafKey.PublicKey, ca.privKey)
	if err != nil {
		return nil, err
	}

	tlsCert := &tls.Certificate{
		Certificate: [][]byte{certBytes},
		PrivateKey:  leafKey,
	}

	return tlsCert, nil
}
